### ISSUE TITLE
Integrate SKOS representations of own vocabularies

### ISSUE THREAD

**Issue by steingod** [metno/mmd#10]
Move existing SKOS representations of own vocabularies into this repository to establish a unified view. After integration, remember to address PIDs.

**Comment by ferrighi** [comment]
Are we getting rid of scivocab? 
Could you explain what you are referring to with respect to PIDs in this context?

**Comment by steingod** [comment]
Could probably rather user URIs, but should anyway be persistent (canonical). The purpose is to use the linked data approach to look up concepts in applications.

**Comment by ferrighi** [comment]
I guess we can close this now?

**Comment by steingod** [comment]
Agree, but do we have PIDs in place?

**Comment by ferrighi** [comment]
all the vocabulary elements from the thesauri have a <skos:Concept rdf:about="https://vocab.met.no/mmd/Dataset_Production_Status/Complete"> which resolve to a landing page. Isn't this what we wanted?

**Comment by steingod** [comment]
Yes. Thanks.
