### ISSUE TITLE
Link publications to datasets

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#101]
We need a way to be able to link possible publications (data paper and scientific publications) to dataset records. An easy way would be to use the related_information element. 
This has 3 subelements: 
"type" -> it is a controlled vocabulary that should be extended with "publication"
"resource" -> this is a url and should be the DOI of that publication or the landing page 
" description" -> this is text and can free (e.g. "the citation string of that publication")

We can extract then information like this to add an section on the landing pages of datasets. It could be something "This dataset is cited in:" and below description + DOI

**Comment by mortenwh** [comment]
This sounds like a useful extension!

**Comment by steingod** [comment]
I fully agree on this (in fact I think I have used it when harvesting information from third party sources). However, it could be that having more "publication types" would be useful? And we need to clarify whether we require a landing page or if a direct link to e.g. a PDF is accepted.
