### ISSUE TITLE
use_constraint 

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#103]
Currently use_constraint has the following structure:
use_constraint
identifier:  CC-BY-4.0
resource: http://spdx.org/licenses/CC-BY-4.0
/use_constraint

with both sub-elements being controlled vocabulary. I suggest to add a new sub-element  "attribution", which is just free text. To this we can translate old records that do not use licenses, and also to align to the suggestions of the ENVRI-FAIR community with is moving towards 
* License identifier
* Link to license:  online resource
* Attribution (free text) [0..*]:  Having the option of having several acknowledgement texts allows for attribution stacking

We can still write that using the controlled vocabulary is the preferred and recommended way, but we can at least have some freedom to record entries that do not fit.

**Comment by steingod** [comment]
I see the issue, but not sure I see Attribution as the correct element to use. Yes we need a strong statement that a license is highly recommended to be FAIR compliant and if present this element is not allowed? If no license is available maybe a freetext element along the lines of non_license_constraint or similar is useful?

**Comment by steingod** [comment]
Following recent discussion I suggest we use license_text instead. If we agree I can prepare a PR on this.

**Comment by steingod** [comment]
PR submitted through #150.

**Comment by steingod** [comment]
Merged PR.
