### ISSUE TITLE
Update controlled vocabularies for collection element

### ISSUE THREAD

**Issue by steingod** [metno/mmd#107]
Several keywords are currently in use but are not listed in the MMD specification. It is suggested to add these (slightly modified compared to what is used today) and update documentation and related systems accordingly.

Keywords missing today relate to SIOS and includes (keys in parenthesis):

- SESS 2018 (SESS2018)
- SESS 2019 (SESS2019)
- SESS 2020  (SESS2019)
- SIOS Core Data (SESSCD)
- SIOS Access Programme (SIOSAP)

In addition we will need a collection for ESA CVL:
- CVL

Any objections or collections missing for now?

**Comment by ferrighi** [comment]
I think it's good, yes.

**Comment by mortenwh** [comment]
Looks good :+1:

**Comment by ferrighi** [comment]
Do you have this already? If not I could do it as I need to test validation of the translated records of sios. I see you call the keys different from what we currently have, i.e. SESS2019 and not SESS_2019. If we stick to this new version I can add correct the translation.

**Comment by steingod** [comment]
No, sorry haven't had time to do this.
