### ISSUE TITLE
Specification of data quality in MMD

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#114]
We need to specificy data quality, e.g., "overall quality of a dataset, any data errors, potential data use and any other information that can help to assess fitness-for-use of the data" (also including provenance). The attached paper summarizes the issue and also contains some use case examples. Another use case could be about the use of ice data from cryo.met.no for navigation (https://github.com/metno/S-ENDA-documentation/issues/197). How can we use MMD to meet these needs?

This is a decision that needs to be documented following the decision template.

[yang2012_an_integrated_view_of_data_quality_in_EO.pdf](https://github.com/metno/mmd/files/5346372/yang2012_an_integrated_view_of_data_quality_in_EO.pdf)

**Comment by mortenwh** [comment]
Ok - this is apparently a bit urgent relating to documentation of ice coverage data. Should we have a meeting to discuss the way forward? @steingod?

**Comment by steingod** [comment]
I haven't had time to dig into old emails referring to GEO and other activities in this area which I think we should. This is information on a discovery level and thus it is very high level. We just need to link with DIF and GEO activities in the area and the key is semantics and a thesaurus. More quantitative statements belong to the use level of data as we already do for remote sensing products.

**Comment by mortenwh** [comment]
Could this be relevant? https://github.com/Informasjonsforvaltning/dqv-ap-no

**Comment by mortenwh** [comment]
@niellaNina - har du anledning til å se noe på dette fremover?

**Comment by mortenwh** [comment]
@niellaNina @ferrighi - is this relevant and possible to follow up in the current sprint?

**Comment by TAlonglong** [comment]
Need to add @niellaNina assignee list for the MMD repo

**Comment by niellaNina** [comment]
I have startet a new branch for this task and have based what I have written in the documentation on what we decided earlier. 

I am currently double checking what would be written under the ISO field for the element, and I have made a first suggestion for the vocabulary. 
There where some extra "a"s in the template for the documentation of the element, those should perhaps be removed?

@ferrighi can you check if I have missed anything more? (the two xsd files are not fixed yet.

**Comment by ferrighi** [comment]
This is great Nina, I would just recommend to call the element and the vocabulary the same (now the element is quality_control and the vocabulary is Data Quality Control), for simplicity. For MM2 you can just write NA, as it is obsolete. I can fix the schema files and push them to this branch. 

My suggestion would be also to add in the description that additional information about data quality control can be provided through the related_information element. Here you could add a type, description and URL for the quality control documentation if needed. This would make sense if detailed info are generally provided for data products on landing pages, manuals or any sort of digital resource.

**Comment by niellaNina** [comment]
Thank you @ferrighi I have made the changes and after a long debate with myself I have ended up with something in the ISO field as well. Not 100% sure if it is correct or not.
