### ISSUE TITLE
Some issues in thesauri definitions

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#116]
Reading out the definition of https://github.com/metno/mmd/blob/master/thesauri/mmd_access_constraints.xml gives a string with many tabulation and line breaks:

```
'\n    A controlled vocabulary to be used to describe the constraints on\n    accessing specific metadata and/or metadata. This is used to determine\n    the exposure of metadata and data internally and externally. Ideallly\n    all datasets (metadata and data) are freely available, but it is\n    acknowledged that some metadata and data may have restrictions that\n    limits their visibility to specific communities only.\n    '
```
This could be avoided by writing long strings as one line only.

The `rdf:about` attribute of `skos:Collection` points to an invalid url (https://wiki.met.no/metamod/vocabularies/Operational_Status). It should be replaced with https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#access_constraint.

Todo:

- [x] Remove line breaks in xml fields of `thesauri/mmd_access_constraints.xml`

- [x] Replace `rdf:about` url of `thesauri/mmd_access_constraints.xml`

- [x] Undo replacement of `rdf:about` url of `thesauri/mmd_access_constraints.xml` (ref comment below)

- [x] Remove line breaks in xml fields of `thesauri/mmd_activity_type.xml`

etc.

**Comment by steingod** [comment]
Line breaks shouldn't matter, but no problem removing them. Concerning the URL I would prefer not using this suggestion but rather wait for the triple store and use that.

**Comment by ferrighi** [comment]
There are no more line breaks in the new thesauri now. @mortenwh can we close this issue now that the thesauri updated has been merged?

**Comment by mortenwh** [comment]
yes - great!
