### ISSUE TITLE
Create datasets for each weather satellite instrument as "parent" of individual acquisitions

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#122]
Each satellite instrument in https://thredds.met.no/thredds/catalog/remotesensingsatellite/polar-swath/catalog.html should be defined as a dataset. These datasets have a parent-child relationship with individual acquisitions.

**Comment by mortenwh** [comment]
Agreed Kartverket about INSPIRE but with national extensions. We will create xml files that they can can check, and we'll have a dialog around that.

- Trygve will write an MMD file for one instrument, and collect xml files for some acquisitions (children) from that instrument
- we will translate to INSPIRE
- then we'll iterate with Kartverket...

**Comment by TAlonglong** [comment]
I don't quite understand this.

So I need to create a parent. We already get the children from the netcdf files with `nc_to_mmd` right?

But how to create a parent?

Will it make sense to make a copy of a child and edit, all timestamps, areas (others?)

How is the child related to the parent? What metadata name?

So if I create a parent for each instrument I get something like this:

avhrr - [metop-a, metop-b, metop-c, noaa-18, noaa-19]
viirs - [npp, noaa-20]
mersi2 - [fengyun-3d]
modis - [aqua, terra]

So the avhrr parent will contain children of 5 different platforms. Is this how we want it? I'm really not sure.

I know we discussed this @mortenwh and @ferrighi, but I will need a quick recap.

**Comment by mortenwh** [comment]
I think it makes sense to copy the existing ones and modify certain elements.

Regarding the parent datasets, I would create the following:

- metop-a avhrr
- metop-b avhrr
- metop-c avhrr
- noaa-18 avhrr
- noaa-19 avhrr
- npp viirs
- noaa-20 viirs
- fengyun-3d mersi-2
- aqua modis
- terra modis

The satellites may have certain differences that makes it sensible to split. We could also make parents of the parents, like a general `avhrr` dataset definition but that might be overkill...

**Comment by ferrighi** [comment]
@TAlonglong yes the parent is usually made from the child as it should contain all the same elements a part from temporal/geographical extent maybe (it depends). The metadata element you need in the child is:

<mmd:related_dataset relation_type="parent">_parent_metadata_identifier_</mmd:related_dataset>

FYI we have a issue (#119) on mmd to improve and extend the relation element between datasets.

**Comment by TAlonglong** [comment]
@ferrighi and @mortenwh I forgot to ask where I should put these resulting parent mmd xml files?

**Comment by TAlonglong** [comment]
And trying to add this information to the netcdf file I'm failing. I need some guidance which attribute names I need to use in the netcdf file to have related_dataset and type in the resulting mmd xml files.

I have tried like this in the netcdf file:

```
		:related_dataset = "uuidtest" ;
		:related_dataset_type = "parent" ;
```
But does not work.

**Comment by mortenwh** [comment]
We'll need to add that to the yaml file as:
```
related_dataset:
  maxOccurs: unbounded
  minOccurs: '0'
  relation_type:
    acdd_ext: related_dataset_relation_type
  id:
    acdd_ext: related_dataset_id
```

Then, the `nc_to_mmd.py` module must probably be updated. Shall I do that?

**Comment by TAlonglong** [comment]
I think that is the most effective.

Did you also see my other questions?

**Comment by mortenwh** [comment]
I made a new issue for the `related_dataset` stuff: https://github.com/metno/py-mmd-tools/issues/64

I think we discussed the other questions, right? :-)

**Comment by TAlonglong** [comment]
We might have discussed it but I can't remember what we agree on.

In the parent dataset, what should I do about the timestamp. Should I update these parents every time I get a new child for the temporal_extent end_time?

And what about last_metadata_update and publication_date?

And also where should these files go? Just manually add them to he mmd repo?

**Comment by mortenwh** [comment]
For future reference: As discussed on zoom, `end_time` is not needed. `last_metadata_update` and `publication_date` can be set to the day when the parent dataset was created. Any update times come if we change it later. The files can be pushed to a branch of the mmd-xml repo on gitlab. Then CI will be run, and the branch can be merged to master if the CI tests pass.

**Comment by mortenwh** [comment]
@TAlonglong - kan denne lukkes nå?
