### ISSUE TITLE
The fileIdentifier from ODA datasets is not universally unique

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#123]
It should be a UUID - see https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#metadata_identifier

**Comment by steingod** [comment]
this raises an hibernating issue that we have had for some time. We should probably add namespace (e.g. no:met:<uuid> or no:met:adc|oda:<uuid> to these. Then they would be easier to handle for harvesting services.

**Comment by ferrighi** [comment]
If we use DNS-reverse namespace we should use "no.met:<uuid>" so with a dot instead of a column, or "no.met:oda:<uuid>". We have seen that use of ":" could create issues when indexing for example in solr, but this could be avoided at the time of indexing.

**Comment by mortenwh** [comment]
should we update the data management handbook with this information as
well? And should it be required, such that we need to test for it?

**Comment by steingod** [comment]
Handling of special characters in ID is now handled during ingestion following the recommendation we have received.It is so far only SolR that has issues on this and we have to handled this for harvested records as well.

**Comment by ElodieFZ** [comment]
@mortenwh so instead of creating a new uuid for each ODA dataset, I should keep the ODA id as the id? And then it would be nc_to_mmd's job to add the id in the mmd file with a namespace?

**Comment by mortenwh** [comment]
No, make the new id in the netcdf file. The ODA id should be `alternate_identifier`.

**Comment by ElodieFZ** [comment]
Ok. That's done. We have both in the netcdf: the ODA it as alternate_identifier and a new uuid as identifier.

**Comment by mortenwh** [comment]
Decision:

- Make ACDD `id` attribute a uuid
- Add ACDD attribute `naming_authority` (will be added as a required attribute in py-mmd-tools)
