### ISSUE TITLE
Geospatial extent/bounds

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#124]
ACDD has `geospatial_bounds` and `geospatial_bounds_crs`. Wouldn't it be more flexible to have that (as Well-Known Text (WKT) representation of geometries) in MMD also, instead of the more specific `geographic_extent/polygon` or `geographic_extent/rectangle`?

**Comment by steingod** [comment]
I have no strong opinion on this, but a change has to be planned well since we have a lot of existing records. I wouldn't consider WKT easy to read for humans though.

**Comment by mortenwh** [comment]
polygon should be sufficient
