### ISSUE TITLE
Some fields in mmd.xsd seems not to be consistent with the documentation

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#125]
1. The [documentation](https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#temporal_extent) says repetition is allowed but `<xs:element name="temporal_extent" type="mmd:temporal_extent_type" maxOccurs="1" minOccurs="0"></xs:element>`. Shouldn't `maxOccurs="unbounded"` and `minOccurs="1"`?
2. From the [documentation](https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#geographic_extentrectangle) I read `geographic_extent` as required. Shouldn't `minOccurs="1"`?
3. [personnel](https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#personnel) is required, so `minOccurs="1"`
4. Repetition is allowed for [data_center](https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html#data_center), i.e., `maxOccurs="unbounded"`
5. `system_specific` elements no longer exist in MMD and should be removed from `mmd.xsd`

**Comment by mortenwh** [comment]
Note: 
- I found the issues here with a [test in py-mmd-tools](https://github.com/metno/py-mmd-tools/blob/issue20_validate_nc/tests/test_mmd_yaml_vs_xsd.py). This still needs to be updated with tests for sub-fields (e.g., `role`and `name` elements for `personnel`)

**Comment by steingod** [comment]
I think we need to think a bit through this and how we manage this. For records being generated internally I totally agree, but having this mandatory for documents harvested will leave all those ignored probably. Any good idea on how we solve that since we are mapping harvested information to MMD prior to ingestion anyway?

**Comment by mortenwh** [comment]
I'm not sure if I understand you correctly but my intention was to focus on internal consistencies between the yaml file for translation between ACDD and MMD in py-mmd-tools and the file `xsd/mmd.xsd`. Do you want to relax the requirements in `mmd.xsd` to be able to harvest metadata that do not fully comply with the requirements in MMD?

**Comment by steingod** [comment]
Yes, we have to do that, else we won't be able to show anything in a distributed system since very few fully comply with the standards. I do however see that this is a bit confusing sometimes. I.e. I wouldn't relax this requirement on datasets we are managing in-house.

**Comment by mortenwh** [comment]
For each item in the list in the description:

1. This should not be a problem to correct, should it?
2. It seems this will only be a problem in `mmd_utils/convert_to_mmd.py`. What if we implement a possibility to manually enter metadata if it is missing? Or we use `lon, lat = (-180, 180), (-90,90)` as default?
3. Same as for 2 (e.g., with "unknown" as default)
4. It should not be a problem to correct this, should it?
5. Not sure about this one, but we could probably just leave it as it is

**Comment by steingod** [comment]
Concerning:

1. I agree on maxOccurs. On minOccurs, this would exclude much data from e.g. NPI. Ideally I agree, but in practise we loose visibility for much data in the current situation.
2. This could be a pragmatic approach.
3. Agree.
4. A dataset could only reside in one data center or? So probably shouldn't be repeatable? Should reflect the host of the metadata? I think there are some datasets that have this, but I think that is erroneous and should be more at the PI level.
5. I think we should remove this.

**Comment by mortenwh** [comment]
> Concerning:
> 
>     1. I agree on maxOccurs. On minOccurs, this would exclude much data from e.g. NPI. Ideally I agree, but in practise we loose visibility for much data in the current situation.

Actually, I noticed after writing my comment, that `minOccurs="1"` and only updated the introduction.. :-P I guess we could used the same approach here - a default value like 1850 to now, or something. We can also add command line arguments to override the defaults in case we're going through a lot of datasets. 

> 
>     2. This could be a pragmatic approach.
> 
>     3. Agree.
> 
>     4. A dataset could only reside in one data center or? So probably shouldn't be repeatable? Should reflect the host of the metadata? I think there are some datasets that have this, but I think that is erroneous and should be more at the PI level.

According to the documentation, repetition is allowed, so `maxOccurs` should be set to "unbounded" for consistency. Updating the xsd should not cause any trouble here. Whether we should change to repetition not allowed, I don't know :)
> 
>     5. I think we should remove this.

**Comment by mortenwh** [comment]
To conclude this issue: I have updated `xsd/mmd.xsd` to strictly reflect the documentation. Then, I have relaxed the requirements in nc_to_mmd.py to reflect the discussion here - see https://github.com/metno/py-mmd-tools/pull/39. I propose to finalize and close https://github.com/metno/py-mmd-tools/pull/39 before we merge the updated `mmd.xsd` to master.

**Comment by mortenwh** [comment]
@steingod @ferrighi - when can this be closed? The new nc_to_mmd.py in py-mmd-tools should handle the exceptions fine :)

**Comment by ferrighi** [comment]
I am not sure I understand the conclusion with respect to the discussion. Mainly the xsd and the pytools are two separate things and mmd files are not only created form netCDF, but also directly from the mdharverster. Is this correct @steingod ? 

For personnel I think it's fine to just add unknown during creation of mmd (but I guess this has to be done in the mdharverster as well, from dif to mmd and iso to mmd), it does not have any real consequences. 
 
For data center, I would probably change the documentation to repetition not allowed since I also don't see the case of data hosted in several data centers, but I'm also find with putting the xsd to unbound. it's not a big deal. 

For time and space in my opinion it is a bit different: I agree, the schema should describe the standard so if an element is mandatory it should be correct in the schema, but is the schema used to validate harvested records before ingestion? if so they will just fail. Setting defaults into nc_to_mmd will not help with this issue. If harvested records are not validated  before ingestion (or the validation failure doesn't stop the indexing) then it is not a problem. 
I am a bit concerned with adding default values, it can be a solution, but when you search for data, you will get wrong matches in the results, i.e. the dataset for a specific spatial extent will popup even if the data do not refer to that location.

**Comment by mortenwh** [comment]
> I am not sure I understand the conclusion with respect to the discussion. Mainly the xsd and the pytools are two separate things and mmd files are not only created form netCDF, but also directly from the mdharverster. Is this correct @steingod ?
> 
This issue is not really about the py-mmd-tools - it's about the agreement between mmd.xsd and the documentation of MMD (i.e., the html/pdf documents). 


> For personnel I think it's fine to just add unknown during creation of mmd (but I guess this has to be done in the mdharverster as well, from dif to mmd and iso to mmd), it does not have any real consequences.

- ok, so a few more tasks related to this issue, then?

> For data center, I would probably change the documentation to repetition not allowed since I also don't see the case of data hosted in several data centers, but I'm also find with putting the xsd to unbound. it's not a big deal.
 
- Fair enough, but then this is a new issue in my opinion...

> For time and space in my opinion it is a bit different: I agree, the schema should describe the standard so if an element is mandatory it should be correct in the schema, but is the schema used to validate harvested records before ingestion? if so they will just fail. Setting defaults into nc_to_mmd will not help with this issue. If harvested records are not validated before ingestion (or the validation failure doesn't stop the indexing) then it is not a problem.

- I don't understand - the default values are meant to be there in order to get the xml files to pass the validation even if some required metadata is missing in the source netcdf files.. How/why won't setting defaults into nc_to_mmd not help with this issue?

> I am a bit concerned with adding default values, it can be a solution, but when you search for data, you will get wrong matches in the results, i.e. the dataset for a specific spatial extent will popup even if the data do not refer to that location.

- Not really - a location between +/-180 degrees longitude and +/-90 degrees latitude will never be wrong. What's the difference if the dataset doesn't have any geolocation?
- Regarding the default times, it should be the same - I doubt we have data from before 1850 if we don't know it (through metadata)

**Comment by steingod** [comment]
Sorry for the delay. I did comment on the relation between the XSD and py-mmd-tools in #126  so won't repeat that here.

Concerning the other issues discussed above:
- So far I have entered Not available in the ACDD interpretation for missing personnel. For harvested records, I haven't done anything.
- I agree on the discussion for data_centre.
- Concerning time and space I think the discussion is slightly different in the sense that a default value will be interpreted as a valid value. I do validate records during ingestion, but will normally ignore many errors. So validation in itself is not the main issue (although not necessarily a useful step as it is now). I am more concerned that a default time or spatial footprint will be misinterpreted by users. And yes we do have data from before 1850. E.g. our historical "ice charts" dates back to the 16th century. In this context I think default values can mislead the potential user. So better having a missing value for that (that would be complicated to handle efficiently in the workflow) or leave them missing.

**Comment by mortenwh** [comment]
I am looking into this again now. Most of it should be ok but I don't want to relax the requirements on time and space metadata. I suggest that we make a new xsd that is one-to-one with the documentation. This could be called `mmd_strict.xsd`, and we can use that one for MET internal datasets. @steingod @ferrighi - what do you think?

**Comment by steingod** [comment]
Agree.
