### ISSUE TITLE
oscar URL schema has changed

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#128]
As reported by the wmo-sat.info/oscar with the launch of OSCAR/Space 2.5 on October 14 2020, the URL schema has changed. As a consequence of this our resource URLs for the platform and instrument vocabularies are not valid any more. 
We need to update the links and consequently the mapping tools to convert old mmd to new mmd specifications.

This task is to decide whether to use OSCAR or own MET solution as reference.

**Comment by ferrighi** [comment]
If there are no objections I have decided to update the oscar links for now.

**Comment by TAlonglong** [comment]
Agree

**Comment by mortenwh** [comment]
@ferrighi - was it correct to close this issue? I reopen it just in case..

**Comment by mortenwh** [comment]
hmm - it seems ok. Please reopen if I'm wrong :)
