### ISSUE TITLE
provide a unique file for thesauri

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#131]
It is recommended to always be able to provide to users a single file with a full vocabulary, and possibly in several formats/serializations. We can: 

1. keep separate vocabulary files, as currently done and set up some automatic action for creation/update of a single file which holds the full collection (but I find it a bit overkill). 
2. remove the single vocabulary files and just maintain a mmd-vocabulary.xml. 

Also in the second case we could have an action that transform rdf/xml to ttl when the xml is modified (and viceversa). 
If we only want one serialization on the mmd repository, the conversion can be made on the vocabulary server, to provide different output files.

**Comment by mortenwh** [comment]
@ferrighi can this be closed?
