### ISSUE TITLE
Create xstl for INSPIRE

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#132]
- [ ] Make sure to find the correct information/schema for INSPIRE.

- [ ] Make sure to use this xslt in the iso-converter

**Comment by ferrighi** [comment]
It seems there is a mandatory keyword to be used from the GEMET vocabulary: https://www.eionet.europa.eu/gemet/en/inspire-themes/
we should try to map to these from what we have in mmd.

**Comment by ferrighi** [comment]
It seems some quality statement (Lineage) is mandatory for spatial dataset and spatial dataset series. 

According  to  the  Implementing  Rules  for  Metadata,  Lineage  is  “a  statement  on  process history  and/or  overall  quality  of  the  spatial  data  set.  Where  appropriate  it  may  include  a statement whether the data set has been validated or quality assured, whether it is the official version (if multiple versions exist), and whether it has legal validity. The value domain of this element is free text.”The process history may be described by information on the source data used and the main transformation steps that took place in creating the current data set (series).

**Comment by ferrighi** [comment]
I am done with a first draft of this xslt script. 
There as few issues to be solved. I will make a list of requirements we need within S-ENDA/MET if we want to be INSPIRE compliant. These are already present in mmd, but are not mandatory. I suggest we leave it as they are, but for locally produced data, we need to make sure that the fields are filled. 
For example for contact point:
 
INSPIRE is more demanding by mandating both the name of the organisation, and a contact e-mail address. 

MMD has only role, name and email mandatory, not the organisation name.

**Comment by ferrighi** [comment]
I have prepared an xslt for INSPIRE based on https://inspire.ec.europa.eu/documents/inspire-metadata-implementing-rules-technical-guidelines-based-en-iso-19115-and-en-iso-1

This provides compiant iso records with INSPIRE profile, as tested on the https://inspire.ec.europa.eu/validator/ for "test suite Common Requirements for ISO/TC 19139:2007 based INSPIRE metadata records".
Several elements are required in INSPIRE that are not required in mmd, thus presence of these elements should be present to comply.

Mandatory Mapping:
=================
title - title
abstract - abstract
resource type - dataset (we don't provide services)
topic category - iso_topic_category
keyword - keywords
geographic bounding box - geographic_extent
Temporal extent - temporal_extent
lineage - we don't have this. We should probably create a default statement (General explanation of the data producer’s knowledge about the lineage of a dataset)
conformity degree - "not evaluated"
conformity specification - default EU regulation
Limitations on public access - access_constraint
Conditions applying to access and use - use_constraint
Responsible party - personnel
Responsible party role - personnel/role
Metadata point of contact - personne with Metadata author role
Metadata date - last_metadata_update
Metadata language - language

Additional Mapping
==================
resource locator - data_access
resource language - language
date of publication - dataset_citation/publication_date
date of last revision - last of last_metadata_update
date of creation - "created" date of last_metadata_update
referenceSystemIdentifier - mmd:geographic_extent/mmd:rectangle/@srsName

List of additional required elements/restrictions:
- for keywords outside  INSPIRE  Spatial  Data  Theme, description of the vocabulary is required (title, date, datetype)
- for keywords, if  only  one  keyword  is  used,  then  INSPIRE  Spatial  Data  Theme is mandatory (we need to find a way to map to this)
- name  of  the  organisation  and  contact email address are mandatory for contact info (organization is not mandatory in mmd)

Open issues:
Unique resource identifier: it should be a doi, or landing page, it's mandatory (none in mmd is). If not a URI in can be a string.
MD_SpatialRepresentation (vector/grid/etc..) is missing
MD_Format (geotiff/kml...) is missing

We need to discuss a bit how to proceed on the few elements we don't have, and investigate a bit further on the requirements. 
I have tested on a weather station dataset now. @TAlonglong I can modify manually your file manually for email and organization, but it would be good to have at least a data_access.

**Comment by TAlonglong** [comment]
OK

Sorry, I had forgotten that nc_to_mmd needs to be run on a netcdf files on thredds to get data_access included.

I will send you a new one.

**Comment by ferrighi** [comment]
We need two more elements from the mmd file to be translated into INSPIRE. 

1) the file_format, this has space into mmd:storage_information/mmd:file_format - @mortenwh I will add an issue in the mmd tool to be added to the nc_to_mmd 
2) the spatial representation, for us either vector or grid. The extraction of this information could be picked up from the featureType. @mortenwh I will open an issue on the mmd tool. 

The additional open issues are: 
1) a lineage statement, but for now a string with "no lineage statement has been provided" is created. 
2) a mapping between internal keywords and GEMET keywords. This require some time.

**Comment by mortenwh** [comment]
See regarding xsd: https://github.com/INSPIRE-MIF/helpdesk-validator/issues/514#issuecomment-784535478

**Comment by iuriemaxim** [comment]
Understanding now that your request is mainly for metadata, not for data, probably this would be of interest to you:

https://github.com/inspire-eu-validation/metadata/blob/2.0/README.md

**Comment by mortenwh** [comment]
The gemet keywords should be added to the CSW service metadata and seems to be presented in the getcapabilities document. Maybe that's enough? I'm following this: https://docs.pycsw.org/en/latest/profiles.html#inspire-extension, and the metadata is added to the pycsw config file.

**Comment by ferrighi** [comment]
That's ok I think, those keywords apply to the service itself. 

Regarding the mmd-to-inspire.xsl I think we should change this issue to something specific for the Norwegian profile. I am completing the transaltion based on feedback from Geonorge. It's really just a few things, mapping to their controlled vocabularies. We need a short discussion with @TAlonglong as well, for including a couple of extra elements the are needed.
