### ISSUE TITLE
add additional translation to iso available in csw

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#141]
This relates to the PR https://github.com/geopython/pycsw/pull/642 added to resolve the csw issue "add support for OGC OpenSearch Earth Observation profile" 

- ``eo:cloudCover``
- ``eo:instrument``
- ``eo:orbitDirection``
- ``eo:orbitNumber``
- ``eo:platform``
- ``eo:processingLevel``
- ``eo:productType``
- ``eo:sensorType``
- ``eo:snowCover``
- ``eo:spectralRange``

mmd-to-iso should map mmd elements to these new fieds.

**Comment by TAlonglong** [comment]
This will also require additions to the netcdf attribute also right?

For the satellite data I handle, I don't have cloudCover nor snowCover. I could add orbit number and direction, but that will require some more work.

The spectral range is included in each channel/dataset/variable in the netcdf, but I guess what is interesting is the overall range, like 0.6µm to 13.4µm.

**Comment by ferrighi** [comment]
None of this is mandatory really. Also we don't have all of these in mmd. I will add only what we have for now.
