### ISSUE TITLE
Additional product types for Copernicus Sentinel products

### ISSUE THREAD

**Issue by hevgyrt** [metno/mmd#147]
Could we add **S2MSI2A** and **S2MSI1C** to the Product types list?

**Comment by ferrighi** [comment]
@hevgyrt can review the content and description or write a link to where I can find these? Would this be ok:

Sentinel-2 MSI Level-1C:  Ortho-rectified and UTM geo-coded Top-of-Atmosphere Reflectance with sub-pixel multispectral and multi-date registration.

Sentinel-2 MSI Level-2A: Ortho-rectified and UTM geo-coded Bottom-of-Atmosphere multi-spectral reflectance. Additional outputs are Aerosol Optical Thickness (AOT) map, Water Vapour (WV) map, Scene Classification map together with Quality Indicators data.

**Comment by hevgyrt** [comment]
This looks good to me!
