### ISSUE TITLE
mmd:data_access

### ISSUE THREAD

**Issue by steingod** [metno/mmd#15]
Check specification of map projection for sub element wms_layers.

**Comment by hevgyrt** [comment]
Not sure if I understand the issue or the relevance. EPSG:4326 (WGS 84 Datum) is the de facto standard in WMS (not 100% sure if it is mandatory). For other projections, we do not have control of what the data providers are using. Hence, I am not sure on what we gain from specifying map projection for the wms_layers elements other than displaying single products in “the most suitable projection”.

**Comment by steingod** [comment]
Yes that is the relevant use for it. Whenever possible we should avoid using EPSG:4326 at high latitudes as it doesn't look good. But of course we could also remove it?

**Comment by hevgyrt** [comment]
I agree that other projections is relevant for e.g. products at high latitude. However, if this issue addresses _if map projection should be added for the sub element wms_layers_, I am not sure what we would gain from this. If we don't gain from it, it will just be another "obstacle" for the data providers..

**Comment by steingod** [comment]
More wise would probably be to update this when checking records. I.e. to check the GetCapabilities document for what is supported and actively use this up front in the presentation of data. I am cllosing this issue for now, we may revisit later when thinking is more mature.
