### ISSUE TITLE
Add controlled vocabulary for access_constraint in xsd files

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#159]
The MMD xsd files don't have the controlled vocabulary for `access_constraint`.

TODO:

- [ ] Add controlled vocabulary to `mmd.xsd` and `mmd_strict.xsd`

**Comment by ferrighi** [comment]
I will add it to the mmd_strict.xsd, we'll keep the string for the mmd.xsd. We should anyway move away from content validation within the schema and use the vocab.met.no for the vocabulary tables.
