### ISSUE TITLE
How to handle weather station data in platform element?

### ISSUE THREAD

**Issue by ElodieFZ** [metno/mmd#168]
We should use the platform element to add station information.

The `long_name` attribute should contain the station name.
Could the `resource` attribute contain the link to WIGOS OSCAR URI?(https://oscar.wmo.int/surface/#/search/station/stationReportDetails/0-20000-0-01492 for example).
Where could the station WIGOS id be stored? In the long_name together with station name?

**Comment by ferrighi** [comment]
For the URI, it's ok with me, although how official that landing page, meaning how persistent the URI is, can be uncertain. 
For the WIGOS id, we do not have support for it in mmd. Generally the concept is that the resource is leading the user to all additional information about the station, including also the ID. But you can put the in the netCDF file I think.

**Comment by mortenwh** [comment]
@elodiefz - can this be closed?
