### ISSUE TITLE
Create xslt to WMO Core profile

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#169]
A mapping to WMO Core profile should be created in form of xslt. Reference documents are: 
https://wis.wmo.int/2012/metadata/WMO_Core_Metadata_Profile_v1.3_Part_1.pdf
and 
https://wis.wmo.int/2012/metadata/WMO_Core_Metadata_Profile_v1.3_Part_2.pdf

**Comment by mortenwh** [comment]
@ferrighi - what is the status of this? wasn't it done in the last sprint?
