### ISSUE TITLE
Consider adding "Not available" or "Unknow" for relevant elements

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#184]
In the mmd schema elements such as operational_status are required with a controlled vocabulary. Currently we have several records indexed with values of "Unknown" and some "Not available". As there is no direct translation from ACDD, and only recommendations to add it in the global attributes of netCDF files, should we consider the possibility to add the Unknow/Not available to the vocabulary list?

**Comment by steingod** [comment]
+1 I would appreciate this as it is hard to populate this when harvesting information.

**Comment by ferrighi** [comment]
Looking at the controlled vocabularies we have currently, I would add this option for:

Mandatory elements in MMD:
-  dataset_production_status (it's mapped from gmd:status, not mandatory) -> "Not available"
-  iso_topic_category (mapped from gmd:topicCategory, not mandatory) -> "Not available"

But also for the Optional MMD:
- O operational_status (not mapped) -> "Not available"
- O activity_type (not mapped - will be obsolete) -> "Not available"

I would also add the "None" to the vocabulary list in the keywords:
- vocabulary "None" (for keywords that do not belong to a vocabulary)

Adding this will make it more smooth also for translation to other standards and make it easier to validate records. 

I will go through the files to be modified in the repository and create a PR.

**Comment by ferrighi** [comment]
This has been included now in #187
