### ISSUE TITLE
Add collection tag

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#190]
The collection tag for the SIOS InfraNor project is currently missing in the documentation and controlled vocabulary. To be consistent with other collection tags I suggest: 
tag: "SIOSIN"
def: Datasets from the SIOS InfraNor Project. 

I can do the editing, but I need a confirmation for the label as currently we are using different tags (SIOS InfraNor, SIOSIN, SIOSInfraNor) for this project.

**Comment by ferrighi** [comment]
I will go ahead and add SIOSIN to the controlled vocabulary. Please update the corresponding harvesting filtering if necessary.

**Comment by steingod** [comment]
I am just wondering whether we should use more explanatory text? I think the very short collection tags is a legacy from the old MM2 and metamod system. It would for sure help us (not least users) if the collection tags are more understandable? the alternative is to use vocab as a lookup for more explanatory text? That would imply changes to metsis-drupal I assume.

**Comment by ferrighi** [comment]
We can surely review the collection tags label and definitions. In the vocab.met.no I have linked also the project URL for some of them (e.g. https://vocab.met.no/mmd/Collection_Keywords/SIOSAP). The link from Drupal to the vocab has been tested and seems to work fine, but it critically depends on indexing only vocabulary terms that are supported in the mmd. This is why we need to first clean up all fields that do not match vocabulary terms.
