### ISSUE TITLE
broken link

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#208]
We are using https://cfconventions.org/standard-names.html as the resource of the CFSTDN vocabulary, this was probably not a good choice, as it does not resolve to a vocabulary, but it was just the landing page of the standard name table overview. This link is now broken. I suggest we change this specification to http://vocab.nerc.ac.uk/standard_name/, this will indeed resolve the cf standard name X provided in the keyword as http://vocab.nerc.ac.uk/standard_name/X

**Comment by steingod** [comment]
Agree.
