### ISSUE TITLE
dif-to-mmd can skip creation of last_metadata_update

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#221]
Currently dif-to-mmd looks for matching "Last_DIF_Revision_Date" and within that template is looking also for DIF_Creation_Date. In case of having only the creation date, the section is bypassed. We need to change: 
xsl:apply-templates select="dif:Last_DIF_Revision_Date" to 
xsl:apply-templates select="dif:Last_DIF_Revision_Date|dif:DIF_Creation_Date"

and the same for the template.

**Comment by steingod** [comment]
Why shouldn't we capture both and convey through multiple update elements? Wouldn't that provide better information for the data consumer?
