### ISSUE TITLE
consider splitting dif-to-mmd into dif9-to-mmd and dif10-to-mmd

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#237]
Since there is significant difference it could be easier to handle harvesting from external sources. This could be done together with reviewing the proposed mapping mmd-dif10 that is still open (https://github.com/metno/mmd/blob/issue_170/mapping/MMD-DIF10.3_controlled_voc.adoc).

**Comment by steingod** [comment]
It is not always clearly defined whether they support DIF 9 or 10 so could be an argument for keeping the current structure that actually works pretty well for me.

**Comment by ferrighi** [comment]
ok. I close this if there is no need. We can improve support for both versions within the same file if necessary.
