### ISSUE TITLE
Dataset series for model data

### ISSUE THREAD

**Issue by mpejcoch** [metno/mmd#44]
ISO19115 defines "dataset series":

> 3.7
> dataset series
> collection of datasets (3.6) sharing common characteristics

We would like to be able to represent these with MMD, but can't find out how to do it.

**Comment by steingod** [comment]
Using related_dataset to link datasets. This currently is only implemented for parent/child relationships, but should also add siblings or other relations. For which purpose are you looking at this?

**Comment by mpejcoch** [comment]
As _dataset_ is very vaguely defined in both MMD and ISO19115 (on purpose I believe) we have datasets ranging from single images (sentinel) to a broad collection of parameters, runs and timesteps (Arome model runs). We'd like to have a possibility to define curated groupings. When we look at datasets at geonorge.no, the list can have both of these dataset types, thus creating a very confusing view, in the current "flat" model there would eventually be hundreds of thousands of satellite images listed and among them a couple of higher level datasets, which we mean we should rather call for _dataset series_.
There is also the _collection_ parameter which we initially thought would be a fit for this purpose, however it seems to be used in a different context today.

**Comment by steingod** [comment]
Dataset as a concept depends on communities, but the highest possible granularity is the generic approach to this and then establishing relationships between datasets, like we do in MMD. In my understanding what you are asking for is the parent child relationships. Collection is used to target various communities/portals/systems and a dataset may/will belong to many collections.

**Comment by mpejcoch** [comment]
I think that parent-child relationship is part of the solution, yes. It does not provide the full answer though as the depth of the relationship tree can vary. Is there a concept of naming the levels in the parent-child relationship tree? Today we have satellite image datasets with no parents, say we add a dataset of Arome model runs which has daily runs as its children. Someone else again might decide to add a dataset with 3 levels (generations). How do we know for which levels does it make sense to be listed together so that we fex. don't provide 150 thousand search results where 149950 are single satellite images and 50 are datasets of a higher order?

**Comment by steingod** [comment]
I am not sure I fully understand this, probably also related to how to define a dataset. To a certain extent I think degrees of freedom has to be limited and it also related to how information is exchanged externally or? Granularity will differ between products and communities, but has to be detailed enough to be useful.

**Comment by mortenwh** [comment]
Isn't this solved with the parent datasets now? @TAlonglong @mpejcoch ?

**Comment by mpejcoch** [comment]
I think we go for something like this:

![Model metadata](https://user-images.githubusercontent.com/2052661/117677615-e63b3d80-b1ae-11eb-964d-3e2795b2f91c.png)

**Comment by mortenwh** [comment]
That looks good!
