### ISSUE TITLE
Add MMD plugin and output schema to pycsw

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#66]
- To avoid translation from MMD to ISO19139 (as required by pyCSW) we need to make a plugin for MMD in pycsw.
- To better suit internal (MET/S-ENDA) needs, we should make an MMD output schema for pycsw.

Defs.: 

- a plugin is the input schema used to ingest metadata in pycsw
- an output schema is the schema used to read from pycsw (currently it works with the INSPIRE profile(?) that was used to make metadata available via the GeoNorge portal)

Other output schemas that should have priority are the following:

- ISO19115 WMO Core Profile supporting GCMD Science Keywords
- ISO19115 Norge Digitalt Profile with requirements.
- GCMD DIF 9.8.x
- GCMD DIF 10

Preferably, the plugin and output schema should reside in separate MET repositories. These codes then import the necessary modules from pycsw.

**Comment by steingod** [comment]
We do also need DIF 9.8.x for NMDC... Not fully sure what pyCSW is exposing.

**Comment by mortenwh** [comment]
> We do also need DIF 9.8.x for NMDC... Not fully sure what pyCSW is exposing.

Added in the above list..
