### ISSUE TITLE
Collection for MET produced data

### ISSUE THREAD

**Issue by TAlonglong** [metno/mmd#71]
As far as I can identify we need a Collection Keyword for Data produced by the core service at MET

This will be used for Satellite data received and processed by MET NORWAY.

So MET NORWAY Core Service: MNCS

- [x] Add suggested collection to controlled vocabulary in ``doc/ch04-md-contrvocabs.adoc``

- [x] Add suggested collection to controlled vocabulary in ``xsd/mmd.xsd``

**Comment by steingod** [comment]
Wouldn't it make sense to have a dedicated project for this as well? Collections are only valid within MET and affiliated services, projects have a room in most standards are often (increasingly) mandatory. Any suggestions for a short and long name to identify governmental core services?

**Comment by TAlonglong** [comment]
GCS, Governmental core service

**Comment by ferrighi** [comment]
@steingod do you have a controlled vocabulary for the project long/short name?

**Comment by steingod** [comment]
Sorry for missing this. No, and neither sure if it is possible. There are too many potential projects. Faceting will help discover inconsistent specifications, but only for our own data, not harvested metadata. We could add a list for datasets MET controls, but we cannot make this mandatory I think. Or?

**Comment by mortenwh** [comment]
I will push a solution for the following suggestion to an issue branch:

METNCS: MET Norway Core Service

As far as I understand, this is for "internal" use, so the "N" for Norway might not be necessary? I think "MET" could be useful to help easy interpretation.

Later, we should have a collection for S-ENDA as well. Is S-ENDA a good name, or rather "GCS: Governmental Core Service" as suggested above?

@steingod @TAlonglong @ferrighi - can you comment before we make a pull request? And have I updated everything needed?

**Comment by ferrighi** [comment]
I think your branch contains all needed elements. For the name I don't think it is a problem for now. METNCS or METNOCS are both fine and easy to change and eventually reindex. I would leave it like you have it for now.
