### ISSUE TITLE
Use pythesint to test vocabularies

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#79]
This is a note for myself. I want to include MMD theasuri files in pythesint. That could be used in testing and for registering metadata with various tools..

**Comment by ferrighi** [comment]
I have not looked at this myself yet, but you could consider checking python-skos (https://github.com/geo-data/python-skos). If you need to read in the resources, so that they become python objects, then it seems you can just get the skos:exactMatch, for mapping with other vocabularies as well.

**Comment by mortenwh** [comment]
This is actually done..
