### ISSUE TITLE
Python code needs to be refactored

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#81]
There is a lot of code repetition in the src-scripts. As part of #74, I am splitting it into `bin` and `mmd_utils`. The executables then go to bin, whereas the modules go to `mmd_utils`.

Modules, classes and functions need to be refactored and tested trough the CI system that we set up in #74.

**Comment by steingod** [comment]
The geonetwork relations should be removed. AFAIK we are not using this anymore or it has at least not been updated for years. For the record, being an old C programmer I have issues with putting scripts in bin directory, but not a big issue.

**Comment by steingod** [comment]
Isn't this issue overdue for closure?

**Comment by mortenwh** [comment]
well - I would say that it can be changed to "Python code needs to be refactored and moved" (to py-mmd-tools). I guess this is a long process, although depending on how much resources we put in.

**Comment by mortenwh** [comment]
I'm closing this issue - it's not that relevant anymore.
