### ISSUE TITLE
All functions in convert_to_mmd.py are currently failing

### ISSUE THREAD

**Issue by mortenwh** [metno/mmd#82]
Please

- [ ] Write unit tests (in tests-folder), and

- [ ] Correct errors

But after issue #74 has been closed.

**Comment by ferrighi** [comment]
This is good and was indeed planned, so that tests can run when updating xsd or xslt. The python code has been written before we had many modifications in the repository and should be revised accordingly. @magnarem wrote the script and might be interested in updating it and follow up on this.

**Comment by mortenwh** [comment]
I close this one as it doesn't seem relevant anymore
