### ISSUE TITLE
Publish the html version for quick reference

### ISSUE THREAD

**Issue by mpejcoch** [metno/mmd#94]
Currently when I need to read a description of an element I navigate to the autogenerated PDF and open it, it would be much faster and easier to have a link to the latest html version.

**Comment by ferrighi** [comment]
The html version mmd-specification.html is generated together with the pdf version in the doc folder. Or are you referring to something else?

**Comment by mpejcoch** [comment]
I know the html is generated, but unless it's served via a webserver then the only way to view it on GitHub is like this:

![Screen Shot 2020-08-31 at 09 01 47](https://user-images.githubusercontent.com/2052661/91691940-d58af000-eb68-11ea-880b-a98130260964.png)

I could download it and open it in a browser, but then it's not really an improvement compared to the pdf file. Or is there some trick I don't know about? How do you usually search in the specification?

**Comment by ferrighi** [comment]
Use https://htmlpreview.github.io/?https://github.com/metno/mmd/blob/master/doc/mmd-specification.html
We could put the link in the README eventually.

**Comment by mpejcoch** [comment]
This works great. Thanks!

**Comment by mortenwh** [comment]
Can this link be added to README?
