### ISSUE TITLE
Extension of collection list

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#95]
As more records within MET are being prepared to follow MMD specifications we are in need of more Collection tags. One was already suggested in #71 , and we need to accommodate also Observational data from ODA, but we need to agree on the granularity of this element within S-ENDA. 
S-ENDA data portal will expose all collections, but we probably need more than just one S-ENDA collection for flexibility. On the other side, if we need to set up different oai-pmh endpoints for each collection as long as "Set" is not supported we should not create a too long or unmanageable list. 
@mortenwh do you have an overview of how many tags we would need, considering the plan of external harvesting of the S-ENDA catalogue?

**Comment by mortenwh** [comment]
I am not sure about the number of tags we need at MET. But I'm pretty sure @mpejcoch and @TAlonglong have opinions regarding their datasets. Anyone else? ODA/frost now seems to be clarified :)

I think we need to separate between MET needs and S-ENDA needs. S-ENDA comes in addition to MET, and we currently don't know if the other institutes would like to use MMD. I therefore suggest to focus on MET first, and then handle partner needs later.

**Comment by steingod** [comment]
I do not think we should anticipate a one to one relation between collections and OAI-PMH end points when using software that doesn't support sets. Only a subset of the collections are relevant for specific end points. Further to this, do we need a specific ODA collection or is that part of MCNS (suggested collection in #71)? I would also suggest that we incorporate the suggestions in #71 to the specification of vocabularies, would need to add such on projects as well then.

**Comment by ferrighi** [comment]
I can prepare a PR for adding the needed collections to the controlled list once we have decided the ones we need.

**Comment by mortenwh** [comment]
We have decided to use the collection name suggested in #71. I close this issue now, and we'll follow up changes in a branch connected to #71.
