### ISSUE TITLE
MMD element for DOI registration

### ISSUE THREAD

**Issue by ferrighi** [metno/mmd#96]
I have a suggestion/request for mapping mmd to datacite. The 6 required fields for Datacite are: 

1) identifier (which is the DOI)-> we get it from datacite
2) creator -> Def: "The main researchers involved in producing the data, or the authors of the publication, in priority order. " We extract personnel with PI role, which is mandatory 
3) title -> we translate mmd:title, which is mandatory 
4) publisher ->we translate mmd:dataset_citation/publisher, which is NOT mandatory
5) publication year -> we translate mmd:dataset_citation/publication_date, which is NOT mandatory 
6) resource type  -> we extract dataset or collection depending on the presence of mmd:end_date

Datacite is a standard for data citation, thus I suggest we use our dataset_citation entries. We have all we need, the only issue is that the elements are not mandatory. We could just add in the documentation "Required: NO (see below)" and add "this element is mandatory for DOI request/record". 

Particularly, the creator is the most relevant issue. The creator does not really match the single PI entry, nor if we add additional personnel, but as datacite uses this entry, it matches the mmd:dataset_citation/authors. 

I already have the xslt to extract "creator" from comma separated author element of mmd.

**Comment by steingod** [comment]
Adding explanatory text like you suggest in order to fulfil DOI requirements would be a very good approach in my understanding. It would also be good to be able to add related material to the landing pages (and integrate in SolR as well). As you mention there are multiple elements in MMD where we may have multiple instances that are not well handled currently.

**Comment by ferrighi** [comment]
That's great, thanks! I will prepare a PR, with the modifications. We already have the updated xslt, I will just add few more corrections. 
The landing page is created using the mmd fileds, so we can add any of those in principle, which related material do you refer to?

**Comment by ferrighi** [comment]
Merged into master.
